export const MENU_BIG_WIDTH: string = '220px';
export const MENU_MIDDLE_WIDTH: string = '50px';
export const MENU_SMALL_WIDTH: string = '0';
export const MENU_LOGO_HEIGHT: string = '156px';
export const MIDDLE_SCREEN_MAX: string = '1024px'; //'940px';
export const MIDDLE_SCREEN_MIN: string = '801px'; //'751px';
export const SMALL_SCREEN_MAX: string = '800px'; //'750px';
export const TOP_HEIGHT: string = '70px';
export const FOOTER_HEIGHT: string = '50px';
export const BIG_LINK_HEIGHT: string = '46px';
export const SUB_LINK_HEIGHT: string = '18px'
export const FA_BIG_FONT_SIZE: string = '28px';
export const FA_SMALL_FONT_SIZE: string = '14px';
export const SUB_MENU_WIDTH: string = '170px';
export const SUB_MENU_TOP_POSITION: string = '166px';